// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseManagementSys.Models;

#nullable disable

namespace PurchaseManagementSys.Migrations
{
    [DbContext(typeof(ConnectionStringClass))]
    partial class ConnectionStringClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PurchaseManagementSys.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_id"), 1L, 1);

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PurchaseManagementSys.Models.Issuance", b =>
                {
                    b.Property<int>("issuance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("issuance_id"), 1L, 1);

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("iss_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qnty")
                        .HasColumnType("int");

                    b.HasKey("issuance_id");

                    b.ToTable("issuances");
                });

            modelBuilder.Entity("PurchaseManagementSys.Models.Item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_id"), 1L, 1);

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("item_id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("PurchaseManagementSys.Models.Purchase", b =>
                {
                    b.Property<int>("pur_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pur_id"), 1L, 1);

                    b.Property<DateTime>("pur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pur_item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pur_price")
                        .HasColumnType("int");

                    b.Property<int>("pur_qty")
                        .HasColumnType("int");

                    b.Property<string>("pur_vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pur_id");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("PurchaseManagementSys.Models.Vendor", b =>
                {
                    b.Property<int>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vendor_id"), 1L, 1);

                    b.Property<string>("vendor_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendor_id");

                    b.ToTable("vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
